version: '3.8'
services:
  gate-video-stream:
    build: 
      dockerfile: ./Dockerfile.prod
    command:
      "./beehive-entrance-video-processor"
    environment:
      - ENV_ID=prod
      - PORT=8400
    ports:
      - 8400:8400
    restart: always
    network_mode: host
