version: '3.9'
services:
  beehive-entrance-video-processor:
    build: 
      dockerfile: ./Dockerfile.dev
    command:
      "go run main.go"
    environment:
      - ENV_ID=dev
      - PORT=8900
    # tty: true
    ports:
      - 8400:8400
    volumes:
      - .:/app/
    restart: always
    network_mode: bridge
    networks:
      - gratheon
networks:
  gratheon:
